export enum ClassesConstants {
  APP = 'app',
  APP_CONTENT = 'app-content',
  GARAGE = 'garage',
  WINNERS = 'winners',
  PAGE_TITLE = 'page-title',
  BUTTON = 'button',
  USUAL_BUTTON = 'usual-button',
  MAIN_BUTTON = 'main-button',
  NAV = 'nav',
  PAGE_NUMBER = 'page-number',
  CAR_SETTING = 'car-setting',
  FIELD = 'field',
  COLOR_INPUT = 'color-input',
  CAR_UPDATE = 'car-update',
}
