export enum ClassesConstants {
  APP = 'app',
  APP_CONTENT = 'app-content',
  GARAGE = 'garage',
  WINNERS = 'winners',
  PAGE_TITLE = 'page-title',
  BUTTON = 'button',
  USUAL_BUTTON = 'usual-button',
  MAIN_BUTTON = 'main-button',
  NAV = 'nav',
  PAGE_NUMBER = 'page-number',
  COLOR_SETTING = 'color-setting',
  COLOR_EXAMPLE = 'color-example',
  COLOR_INPUT = 'color-input',
}
