export enum ContentConstants {
  GARAGE = 'Garage',
  WINNERS = 'Winners',
  TO_GARAGE = 'to garage',
  TO_WINNERS = 'to winners',
  PAGE = 'Page',
  UPDATE = 'update',
  CREATE = 'create',
  RACE = 'race',
  RESET = 'reset',
  GENERATE_CARDS = 'generate cards',
  SELECT = 'select',
  REMOVE = 'remove',
  PREV = 'prev',
  NEXT = 'next',
  START_BTN = 'a',
  STOP_BTN = 'b',
}
